from __future__ import annotations

import sqlite3
from typing import Any


LATEST_SCHEMA_VERSION = 3


SQLITE_V1 = """
CREATE TABLE IF NOT EXISTS tenants (
    tenant_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('active', 'suspended')),
    created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS users (
    user_id TEXT PRIMARY KEY,
    display_name TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('active', 'disabled')),
    created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS memberships (
    tenant_id TEXT NOT NULL REFERENCES tenants(tenant_id),
    user_id TEXT NOT NULL REFERENCES users(user_id),
    role TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (tenant_id, user_id)
);
CREATE TABLE IF NOT EXISTS api_tokens (
    token_id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    token_prefix TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('active', 'revoked')),
    created_at TEXT NOT NULL,
    expires_at TEXT,
    last_used_at TEXT,
    FOREIGN KEY (tenant_id, user_id)
        REFERENCES memberships(tenant_id, user_id)
);
CREATE TABLE IF NOT EXISTS knowledge_spaces (
    tenant_id TEXT NOT NULL REFERENCES tenants(tenant_id),
    space_id TEXT NOT NULL,
    name TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('active', 'archived')),
    created_by TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (tenant_id, space_id),
    FOREIGN KEY (tenant_id, created_by)
        REFERENCES memberships(tenant_id, user_id)
);
CREATE TABLE IF NOT EXISTS audit_events (
    event_id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    actor_user_id TEXT NOT NULL,
    action TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    resource_id TEXT NOT NULL,
    trace_id TEXT NOT NULL,
    outcome TEXT NOT NULL,
    details_json TEXT NOT NULL
);
"""

SQLITE_V3 = """
CREATE INDEX IF NOT EXISTS idx_tokens_hash
    ON api_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_tokens_tenant_status
    ON api_tokens(tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_memberships_tenant_status
    ON memberships(tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_audit_tenant_event
    ON audit_events(tenant_id, event_id DESC);
CREATE INDEX IF NOT EXISTS idx_audit_tenant_timestamp
    ON audit_events(tenant_id, timestamp DESC);
"""

POSTGRES_V1 = """
CREATE TABLE IF NOT EXISTS tenants (
    tenant_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('active', 'suspended')),
    created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS users (
    user_id TEXT PRIMARY KEY,
    display_name TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('active', 'disabled')),
    created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS memberships (
    tenant_id TEXT NOT NULL REFERENCES tenants(tenant_id),
    user_id TEXT NOT NULL REFERENCES users(user_id),
    role TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (tenant_id, user_id)
);
CREATE TABLE IF NOT EXISTS api_tokens (
    token_id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    token_prefix TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('active', 'revoked')),
    created_at TEXT NOT NULL,
    expires_at TEXT,
    last_used_at TEXT,
    FOREIGN KEY (tenant_id, user_id)
        REFERENCES memberships(tenant_id, user_id)
);
CREATE TABLE IF NOT EXISTS knowledge_spaces (
    tenant_id TEXT NOT NULL REFERENCES tenants(tenant_id),
    space_id TEXT NOT NULL,
    name TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('active', 'archived')),
    created_by TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (tenant_id, space_id),
    FOREIGN KEY (tenant_id, created_by)
        REFERENCES memberships(tenant_id, user_id)
);
CREATE TABLE IF NOT EXISTS audit_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    actor_user_id TEXT NOT NULL,
    action TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    resource_id TEXT NOT NULL,
    trace_id TEXT NOT NULL,
    outcome TEXT NOT NULL,
    details_json TEXT NOT NULL
);
"""

POSTGRES_V3 = """
CREATE INDEX IF NOT EXISTS idx_tokens_hash
    ON api_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_tokens_tenant_status
    ON api_tokens(tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_memberships_tenant_status
    ON memberships(tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_audit_tenant_event
    ON audit_events(tenant_id, event_id DESC);
CREATE INDEX IF NOT EXISTS idx_audit_tenant_timestamp
    ON audit_events(tenant_id, timestamp DESC);
"""


def _sqlite_has_table(connection: sqlite3.Connection, table: str) -> bool:
    row = connection.execute(
        "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?",
        (table,),
    ).fetchone()
    return row is not None


def _sqlite_has_membership_status(connection: sqlite3.Connection) -> bool:
    if not _sqlite_has_table(connection, "memberships"):
        return False
    return "status" in {
        row["name"]
        for row in connection.execute("PRAGMA table_info(memberships)").fetchall()
    }


def apply_sqlite_migrations(connection: sqlite3.Connection) -> int:
    """Apply every pending migration in one SQLite transaction."""

    connection.execute("BEGIN IMMEDIATE")
    try:
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS schema_metadata (
                key TEXT PRIMARY KEY,
                value TEXT NOT NULL
            )
            """
        )
        row = connection.execute(
            "SELECT value FROM schema_metadata WHERE key = 'schema_version'"
        ).fetchone()
        if row is not None:
            current = int(row["value"])
        elif _sqlite_has_table(connection, "tenants"):
            current = 2 if _sqlite_has_membership_status(connection) else 1
        else:
            current = 0

        if current > LATEST_SCHEMA_VERSION:
            raise RuntimeError(
                f"database schema {current} is newer than application schema "
                f"{LATEST_SCHEMA_VERSION}"
            )
        # Re-run the idempotent baseline so partially initialized legacy
        # databases receive every table before incremental alterations/indexes.
        _execute_sqlite_script(connection, SQLITE_V1)
        if current < 1:
            current = 1
        if current < 2:
            connection.execute(
                """
                ALTER TABLE memberships
                ADD COLUMN status TEXT NOT NULL DEFAULT 'active'
                CHECK (status IN ('active', 'disabled'))
                """
            )
            current = 2
        if current < 3:
            _execute_sqlite_script(connection, SQLITE_V3)
            current = 3
        connection.execute(
            """
            INSERT INTO schema_metadata(key, value)
            VALUES ('schema_version', ?)
            ON CONFLICT(key) DO UPDATE SET value = excluded.value
            """,
            (str(current),),
        )
        connection.commit()
        return current
    except Exception:
        connection.rollback()
        raise


def _execute_sqlite_script(connection: sqlite3.Connection, script: str) -> None:
    for statement in (part.strip() for part in script.split(";")):
        if statement:
            connection.execute(statement)


def apply_postgres_migrations(connection: Any) -> int:
    """Apply PostgreSQL migrations while holding a transaction advisory lock."""

    try:
        connection.execute(
            "SELECT pg_advisory_xact_lock(hashtext(%s))",
            ("ruichuang_control_plane_schema",),
        )
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS schema_metadata (
                key TEXT PRIMARY KEY,
                value TEXT NOT NULL
            )
            """
        )
        row = connection.execute(
            "SELECT value FROM schema_metadata WHERE key = %s",
            ("schema_version",),
        ).fetchone()
        if row is not None:
            current = int(row["value"])
        else:
            tenant_table = connection.execute(
                "SELECT to_regclass('public.tenants') AS table_name"
            ).fetchone()
            if tenant_table and tenant_table["table_name"]:
                status_column = connection.execute(
                    """
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'memberships'
                      AND column_name = 'status'
                    """
                ).fetchone()
                current = 2 if status_column else 1
            else:
                current = 0

        if current > LATEST_SCHEMA_VERSION:
            raise RuntimeError(
                f"database schema {current} is newer than application schema "
                f"{LATEST_SCHEMA_VERSION}"
            )
        _execute_postgres_script(connection, POSTGRES_V1)
        if current < 1:
            current = 1
        if current < 2:
            connection.execute(
                """
                ALTER TABLE memberships
                ADD COLUMN status TEXT NOT NULL DEFAULT 'active'
                CHECK (status IN ('active', 'disabled'))
                """
            )
            current = 2
        if current < 3:
            _execute_postgres_script(connection, POSTGRES_V3)
            current = 3
        connection.execute(
            """
            INSERT INTO schema_metadata(key, value)
            VALUES ('schema_version', %s)
            ON CONFLICT(key) DO UPDATE SET value = EXCLUDED.value
            """,
            (str(current),),
        )
        connection.commit()
        return current
    except Exception:
        connection.rollback()
        raise


def _execute_postgres_script(connection: Any, script: str) -> None:
    for statement in (part.strip() for part in script.split(";")):
        if statement:
            connection.execute(statement)
