from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class ControlPlaneStore(Protocol):
    """Persistence contract used by the enterprise control-plane service."""

    backend: str

    def health(self) -> dict[str, Any]: ...

    def create_tenant_owner(self, **kwargs: Any) -> None: ...

    def add_membership(self, **kwargs: Any) -> dict[str, Any]: ...

    def membership(self, tenant_id: str, user_id: str) -> dict[str, Any] | None: ...

    def list_members(self, tenant_id: str) -> list[dict[str, Any]]: ...

    def active_owner_count(self, tenant_id: str) -> int: ...

    def update_membership(self, **kwargs: Any) -> dict[str, Any]: ...

    def insert_token(self, **kwargs: Any) -> dict[str, Any]: ...

    def identity_for_hash(self, token_hash: str) -> dict[str, Any] | None: ...

    def list_tokens(self, tenant_id: str) -> list[dict[str, Any]]: ...

    def revoke_token(self, **kwargs: Any) -> dict[str, Any]: ...

    def create_knowledge_space(self, **kwargs: Any) -> dict[str, Any]: ...

    def knowledge_space(
        self,
        tenant_id: str,
        space_id: str,
    ) -> dict[str, Any] | None: ...

    def list_knowledge_spaces(self, tenant_id: str) -> list[dict[str, Any]]: ...

    def append_audit(self, **kwargs: Any) -> None: ...

    def list_audit(
        self,
        tenant_id: str,
        *,
        limit: int = 100,
    ) -> list[dict[str, Any]]: ...
