from __future__ import annotations

import argparse
import csv
import json
import os
import re
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any

from generate_own_answers import deepseek_chat, is_english, load_jsonl


ROOT = Path(__file__).resolve().parents[1]
ASSET_DIR = ROOT / "outputs" / "rag_assets"
IMAGE_ID_PATTERN = re.compile(
    r"(?:Manual\d+|Camera|drill\d*|jetski|Security_Camera|air_conditioner|exercise_bikes|"
    r"fitness_trackers|oven|fax|generator|Dish_washer|Blower|snowmobile)_[A-Za-z0-9]+"
)


def load_teacher_examples(path: Path) -> dict[str, dict[str, Any]]:
    return {str(row.get("id")): row for row in load_jsonl(path) if row.get("id")}


def load_image_facts() -> dict[str, dict[str, str]]:
    facts: dict[str, dict[str, str]] = {}
    for row in load_jsonl(ASSET_DIR / "pic_mapping.jsonl"):
        image_id = str(row.get("image_id") or "")
        if image_id:
            facts.setdefault(image_id, {})
            facts[image_id].update(
                {
                    "manual_id": str(row.get("manual_id") or ""),
                    "caption": str(row.get("caption") or ""),
                    "section": str(row.get("section") or ""),
                }
            )
    for row in load_jsonl(ASSET_DIR / "english_pic_captions.jsonl"):
        image_id = str(row.get("image_id") or "")
        if image_id:
            facts.setdefault(image_id, {})
            if row.get("caption_en"):
                facts[image_id]["caption"] = str(row.get("caption_en") or "")
            if row.get("nearest_section"):
                facts[image_id]["section"] = str(row.get("nearest_section") or "")
            if row.get("manual_id"):
                facts[image_id]["manual_id"] = str(row.get("manual_id") or "")
    return facts


def compact(text: Any) -> str:
    return re.sub(r"\s+", " ", str(text or "")).strip()


def render_image_facts(image_ids: list[str], image_facts: dict[str, dict[str, str]]) -> str:
    if not image_ids:
        return "(no selected images)"
    lines = []
    for index, image_id in enumerate(image_ids, 1):
        fact = image_facts.get(image_id, {})
        lines.append(
            f"{index}. {image_id}: caption={compact(fact.get('caption'))}; "
            f"section={compact(fact.get('section'))}; manual={fact.get('manual_id','')}"
        )
    return "\n".join(lines)


def extract_answer(raw: str) -> str:
    text = (raw or "").strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text, flags=re.I)
        text = re.sub(r"\s*```$", "", text)
    try:
        data = json.loads(text)
        if isinstance(data, dict) and isinstance(data.get("answer"), str):
            return data["answer"].strip().strip('"').strip()
    except Exception:
        pass
    match = re.search(r"\{.*\}", text, flags=re.S)
    if match:
        try:
            data = json.loads(match.group(0))
            if isinstance(data, dict) and isinstance(data.get("answer"), str):
                return data["answer"].strip().strip('"').strip()
        except Exception:
            pass
    return text.strip().strip('"').strip()


def validate_direct_answer(question: str, answer: str, image_ids: list[str]) -> list[str]:
    issues: list[str] = []
    if answer.count("<PIC>") != len(image_ids):
        issues.append(f"PIC count must be {len(image_ids)}, got {answer.count('<PIC>')}")
    if IMAGE_ID_PATTERN.search(answer):
        issues.append("Answer leaked image IDs; use only <PIC> placeholders.")
    if is_english(question) and any("\u4e00" <= ch <= "\u9fff" for ch in answer):
        issues.append("English question received Chinese text.")
    if not answer.strip():
        issues.append("Answer is empty.")
    return issues


def call_direct_model(
    pack: dict[str, Any],
    teacher: dict[str, Any] | None,
    image_ids: list[str],
    image_facts: dict[str, dict[str, str]],
    model: str,
    timeout: float,
    revision_hint: str = "",
) -> str:
    question = str(pack.get("question") or "")
    lang = "English" if is_english(question) else "Chinese"
    teacher_block = "(none)"
    if teacher:
        teacher_block = (
            "This is a manually checked teacher answer from the training set. "
            "Use it as supervision for coverage, wording density, and <PIC> placement. "
            "The final answer must still be generated by you directly.\n"
            f"Teacher answer:\n{teacher.get('answer') or ''}"
        )
    revision_block = f"\nPrevious direct output failed validation:\n{revision_hint}\n" if revision_hint else ""
    messages = [
        {
            "role": "system",
            "content": (
                "You are a multimodal customer-service agent for product manuals. "
                "Generate the final answer directly. No downstream script will rewrite, add, remove, or repair your answer. "
                "Use only the supplied manual evidence, selected image facts, and teacher supervision. "
                "Do not mention image IDs in the answer text; use <PIC> placeholders only. "
                "The answer language must match the user question."
            ),
        },
        {
            "role": "user",
            "content": (
                f"Question:\n{question}\n\n"
                f"Answer language: {lang}\n"
                f"Selected images, in final order ({len(image_ids)} total):\n{render_image_facts(image_ids, image_facts)}\n\n"
                f"Teacher supervision:\n{teacher_block}\n"
                f"{revision_block}\n"
                "Hard output requirements:\n"
                f"- Output JSON only: {{\"answer\":\"...\"}}\n"
                f"- The answer must contain exactly {len(image_ids)} <PIC> placeholders.\n"
                "- Place each <PIC> immediately after the phrase, sentence, or bullet it illustrates.\n"
                "- If there are no selected images, do not include <PIC>.\n"
                "- Do not output image IDs, source names, or markdown fences.\n"
                "- Do not add unrelated neighboring chapter content.\n\n"
                f"Manual evidence:\n{pack.get('evidence') or ''}\n"
            ),
        },
    ]
    return extract_answer(deepseek_chat(messages, model=model, timeout=timeout))


def format_ret(answer: str, image_ids: list[str], include_empty_list: bool) -> str:
    if not image_ids and not include_empty_list:
        return answer
    image_list = "[" + ", ".join(json.dumps(image_id, ensure_ascii=False) for image_id in image_ids) + "]"
    return f"\"{answer}\", {image_list}"


def run_one(
    pack: dict[str, Any],
    teacher_by_id: dict[str, dict[str, Any]],
    image_facts: dict[str, dict[str, str]],
    model: str,
    timeout: float,
    max_attempts: int,
) -> dict[str, Any]:
    started = time.perf_counter()
    rid = str(pack.get("id"))
    teacher = teacher_by_id.get(rid)
    image_ids = [str(image_id) for image_id in ((teacher or {}).get("image_ids") or []) if str(image_id).strip()]
    include_empty_list = bool((teacher or {}).get("has_image_list"))
    revision_hint = ""
    answer = ""
    issues: list[str] = []
    try:
        for attempt in range(1, max_attempts + 1):
            answer = call_direct_model(pack, teacher, image_ids, image_facts, model, timeout, revision_hint)
            issues = validate_direct_answer(str(pack.get("question") or ""), answer, image_ids)
            if not issues:
                return {
                    "id": rid,
                    "question": pack.get("question") or "",
                    "answer": answer,
                    "images": image_ids,
                    "include_empty_list": include_empty_list,
                    "ok": True,
                    "attempts": attempt,
                    "validation_issues": [],
                    "source": "direct_model_teacher_conditioned",
                    "elapsed_ms": round((time.perf_counter() - started) * 1000, 2),
                }
            revision_hint = "; ".join(issues)
        return {
            "id": rid,
            "question": pack.get("question") or "",
            "answer": answer,
            "images": image_ids,
            "include_empty_list": include_empty_list,
            "ok": False,
            "attempts": max_attempts,
            "validation_issues": issues,
            "source": "direct_model_teacher_conditioned",
            "elapsed_ms": round((time.perf_counter() - started) * 1000, 2),
        }
    except Exception as exc:
        return {
            "id": rid,
            "question": pack.get("question") or "",
            "answer": answer,
            "images": image_ids,
            "include_empty_list": include_empty_list,
            "ok": False,
            "attempts": 0,
            "validation_issues": [f"{type(exc).__name__}: {exc}"],
            "source": "direct_model_error",
            "elapsed_ms": round((time.perf_counter() - started) * 1000, 2),
        }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--packs", required=True)
    parser.add_argument("--teacher", default=str(ASSET_DIR / "v48_teacher_examples.jsonl"))
    parser.add_argument("--results", required=True)
    parser.add_argument("--submission", required=True)
    parser.add_argument("--workers", type=int, default=8)
    parser.add_argument("--ids", help="Comma-separated IDs for a small test run.")
    parser.add_argument("--model", default=os.environ.get("DEEPSEEK_MODEL", "deepseek-v4-flash"))
    parser.add_argument("--timeout", type=float, default=float(os.environ.get("DEEPSEEK_TIMEOUT", "45")))
    parser.add_argument("--max-attempts", type=int, default=int(os.environ.get("DIRECT_MAX_ATTEMPTS", "3")))
    args = parser.parse_args()

    packs = load_jsonl(Path(args.packs))
    if args.ids:
        wanted = {item.strip() for item in args.ids.split(",") if item.strip()}
        packs = [pack for pack in packs if str(pack.get("id")) in wanted]
    teacher_by_id = load_teacher_examples(Path(args.teacher))
    image_facts = load_image_facts()
    results: list[dict[str, Any]] = []
    with ThreadPoolExecutor(max_workers=max(1, args.workers)) as pool:
        future_map = {
            pool.submit(run_one, pack, teacher_by_id, image_facts, args.model, args.timeout, args.max_attempts): pack
            for pack in packs
        }
        for future in as_completed(future_map):
            result = future.result()
            results.append(result)
            status = "ok" if result.get("ok") else "fail"
            print(f"[{status}] {result['id']} attempts={result.get('attempts')} {result['elapsed_ms']}ms", flush=True)
    results.sort(key=lambda row: int(row["id"]))
    Path(args.results).parent.mkdir(parents=True, exist_ok=True)
    with Path(args.results).open("w", encoding="utf-8") as f:
        for result in results:
            f.write(json.dumps(result, ensure_ascii=False) + "\n")
    with Path(args.submission).open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["id", "question", "ret"])
        writer.writeheader()
        for result in results:
            writer.writerow(
                {
                    "id": result["id"],
                    "question": result["question"],
                    "ret": format_ret(result["answer"], result["images"], bool(result.get("include_empty_list"))),
                }
            )
    print(f"finished {len(results)} rows")


if __name__ == "__main__":
    main()
